[access_switches]
ACC-TOAA-G ansible_host=10.100.1.20
ACC-TOAA-1 ansible_host=10.100.1.21
ACC-TOAA-2 ansible_host=10.100.1.22
ACC-TOAA-3 ansible_host=10.100.1.23
ACC-TOAE-G ansible_host=10.100.1.30
ACC-TOAE-1 ansible_host=10.100.1.31
ACC-TOAE-2 ansible_host=10.100.1.32
ACC-TOAE-3 ansible_host=10.100.1.33

[access_switches:vars]
ansible_network_os=ios
ansible_connection=network_cli
ansible_user=admin
ansible_password=cisco
ansible_become=yes
ansible_become_method=enable
ansible_become_password=cisco